@props(['currentOccupation' => ''])

<div>
    <label for="profession" class="block text-sm font-medium text-gray-700 mb-1">
        Profession
    </label>

    <input
        id="profession"
        name="occupation"
        list="occupation-options"
        class="w-full px-3 py-2 border border-gray-300 rounded-md
               focus:outline-none focus:ring-2 focus:ring-blue-500
               @error('occupation') border-red-500 @enderror"
        placeholder="Select or type your profession"
        value="{{ old('occupation', $currentOccupation) }}"
    >

    <datalist id="occupation-options">
        <option value="Accountant">
        <option value="Actor">
        <option value="Actress">
        <option value="Actuary">
        <option value="Administrator">
        <option value="Advertiser">
        <option value="Advocate">
        <option value="Agricultural Worker">
        <option value="Agronomist">

        <option value="Architect">
        <option value="Army Officer">
        <option value="Artisan">
        <option value="Artist">
        <option value="Auditor">
        <option value="Auto Electrician">
        <option value="Auto Mechanic">
        <option value="Aviation Worker">
        <option value="Baker">
        <option value="Banker">
        <option value="Barber">
        <option value="Barrister">
        <option value="Biochemist">
        <option value="Biologist">
        <option value="Blogger">
        <option value="Bricklayer">
        <option value="Builder">
        <option value="Business">
        <option value="Business Analyst">
        <option value="Business Owner">
        <option value="Carpenter">
        <option value="Caterer">
        <option value="Chaplain">
        <option value="Chef">
        <option value="Chemical Engineer">
        <option value="Chemist">
        <option value="Civil Engineer">
        <option value="Civil Servant">
        <option value="Cleaner">
        <option value="Clergy">
        <option value="Comedian">
        <option value="Community Health Worker">
        <option value="Computer Analyst">
        <option value="Computer Operator">
        <option value="Computer Scientist">
        <option value="Computer Technician">
        <option value="Consultant">
        <option value="Content Creator">
        <option value="Contractor">
        <option value="Cook">
        <option value="Corp Member">
        <option value="Corp Member NYSC">
        <option value="Customer Service">
        <option value="Customs Officer">
        <option value="Driver">
        <option value="Data Analyst">
        <option value="Data Scientist">
        <option value="Database Administrator">
        <option value="Delivery Officer">
        <option value="Dentist">
        <option value="Development Worker">
        <option value="Dietitian">
        <option value="Digital Marketer">
        <option value="Driver">
        <option value="Economist">
        <option value="Editor">
        <option value="Electrical Engineer">
        <option value="Electrician">
        <option value="Emergency Responder">
        <option value="Engineer">
        <option value="Entertainer">
        <option value="Entrepreneur">
        <option value="Environmentalist">
        <option value="Estate Surveyor">
        <option value="Evangelist">
        <option value="Event Planner">
        <option value="Farmer">
        <option value="Fashion Designer">
        <option value="Financial Analyst">
        <option value="Financial Consultant">
        <option value="First Aid Specialist">
        <option value="First Aid Trainer">
        <option value="Fisherman">
        <option value="Fitness Trainer">
        <option value="Footballer">
        <option value="Furniture Maker">
        <option value="Geologist">
        <option value="Graphics Designer">
        <option value="Gym Instructor">
        <option value="Hairdresser">
        <option value="Health & Safety Officer">
        <option value="Healthcare Worker">
        <option value="Housewife">
        <option value="Human Resource Specialist">
        <option value="Humanitarian Worker">
        <option value="Imam">
        <option value="Immigration Officer">
        <option value="Insurance Agent">
        <option value="Interior Designer">
        <option value="IT Professional">
        <option value="Job Seeker">
        <option value="Journalist">
        <option value="Judge">
        <option value="Lab Scientist">
        <option value="Lab Technician">
        <option value="Laundry Worker">
        <option value="Lawyer">
        <option value="Lecturer">
        <option value="Legal Assistant">
        <option value="Librarian">
        <option value="Livestock Worker">
        <option value="Logistics Officer">
        <option value="Magistrate">
        <option value="Makeup Artist">
        <option value="Marine Engineer">
        <option value="Marketer">
        <option value="Mason">
        <option value="Mechanic">
        <option value="Mechanical Engineer">
        <option value="Medical Doctor">
        <option value="Medical Laboratory Scientist">
        <option value="Midwife">
        <option value="Missionary">
        <option value="Model">
        <option value="Musician">
        <option value="Nurse">
        <option value="Nutritionist">
        <option value="Optometrist">
        <option value="Painter">
        <option value="Pastor">
        <option value="Petroleum Engineer">
        <option value="Pharmacist">
        <option value="Photographer">
        <option value="Photojournalist">
        <option value="Physiotherapist">
        <option value="Pilot">
        <option value="Plumber">
        <option value="Police Officer">
        <option value="Poultry Farmer">
        <option value="Printer">
        <option value="Product Designer">
        <option value="Product Manager">
        <option value="Project Manager">
        <option value="Public Health Specialist">
        <option value="Quantity Surveyor">
        <option value="Radiographer">
        <option value="Real Estate Agent">
        <option value="Receptionist">
        <option value="Researcher">
        <option value="Retired">
        <option value="Sales Representative">
        <option value="School Administrator">
        <option value="Secretary">
        <option value="Security Officer">
        <option value="Self-Employed">
        <option value="Shop Owner">
        <option value="Social Media Manager">
        <option value="Social Worker">
        <option value="Software Developer">
        <option value="Software Engineer">
        <option value="Soldier">
        <option value="Statistician">
        <option value="Student">
        <option value="Surveyor">
        <option value="System Analyst">
        <option value="Tailor">
        <option value="Teacher">
        <option value="Technical Support Specialist">
        <option value="Textile Designer">
        <option value="Town Planner">
        <option value="Trader">
        <option value="Transport Worker">
        <option value="Unemployed">
        <option value="Veterinarian">
        <option value="Videographer">
        <option value="Waiter">
        <option value="Waitress">
        <option value="Warehouse Worker">
        <option value="Weaver">
        <option value="Welder">
        <option value="Writer">
        <option value="X-ray Technician">

            <!-- Last catch-all -->
        <option value="Other">
    </datalist>

    @error('occupation')
    <p class="text-red-500 text-xs mt-1">{{ $message }}</p>
    @enderror
</div>
